<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:context="http://www.springframework.org/schema/context"
	xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
		http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-3.1.xsd">

	<context:property-placeholder
		location="classpath:database/jdbc.properties" />

	<bean id="dataSource" class="com.zaxxer.hikari.HikariDataSource"
		destroy-method="close">
		<constructor-arg>
			<bean class="com.zaxxer.hikari.HikariConfig">
				<constructor-arg>
					<props>
						<prop key="jdbcUrl">${jdbc.url}</prop>
						<prop key="username">${jdbc.username}</prop>
						<prop key="password">${jdbc.password}</prop>
					</props>
				</constructor-arg>
				<property name="driverClassName"
					value="${jdbc.driverClassName}" />
				<property name="minimumIdle" value="5" />
				<property name="maximumPoolSize" value="10" />
				<property name="connectionTestQuery"
					value="select 1 from sys.dual" />
				<property name="connectionTimeout" value="300000" />
			</bean>
		</constructor-arg>
	</bean>

	<bean id="jdbcTemplate"
		class="org.springframework.jdbc.core.JdbcTemplate">
		<property name="dataSource" ref="dataSource" />
	</bean>
	
	<context:component-scan base-package="com.ppt" />

	<bean id="exceptionResolver"
		class="org.springframework.web.servlet.handler.SimpleMappingExceptionResolver">
		<property name="exceptionMappings">
			<props>
				<prop key="java.lang.RuntimeException">
					error/runtime
				</prop>
			</props>
		</property>
		<property name="defaultErrorView" value="error/default" />
	</bean>


</beans>